name: Terraform CosmosDB CI/CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (dev or prod)"
        required: true
        default: "dev"

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    #environment: ${{ github.event.inputs.environment }}

    env:
      ENV: ${{ github.event.inputs.environment }}

    defaults:
      run:
        working-directory: terraform/environments/${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init -backend-config=backend.tf

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars" -out=tfplan.out

      - name: Generate Cost Estimate with Infracost
        uses: infracost/actions@v2
        with:
          path: terraform/environments/${{ env.ENV }}
          terraform_plan_file: tfplan.out
          terraform_workspace: ${{ env.ENV }}
          infracost_api_key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Email Cost Estimate
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Infracost Report for Cosmos DB - ${{ env.ENV }}"
          to: prathyusha.y@algorims.com
          from: GitHub Terraform CI
          body: |
            Please find the attached cost estimation for the Cosmos DB infrastructure changes.
          attachments: infracost-report.json

      - name: Terraform Apply (with approval for all environments)
        environment: ${{ github.event.inputs.environment }}   
        if: github.event.inputs.confirm_apply == 'yes'
        run: terraform apply -auto-approve tfplan.out