name: Terraform CosmosDB CI/CD

on:
  push:
    branches:
      - stage
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (dev or prod)"
        required: true
        default: "dev"
      confirm_apply:
        description: "Type 'yes' to apply resources"
        required: true
        default: "no"

jobs:
  plan:
    name: Terraform Plan and Cost Estimate
    runs-on: ubuntu-latest

    env:
       ENV: ${{ github.event.inputs.environment || 'dev' }}

    defaults:
      run:
        working-directory: terraform/environments/${{ env.ENV }}
    outputs:
      tfplan-exists: ${{ steps.tfplan.outputs.plan_created }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # - name: Azure Login
      #   uses: azure/login@v2
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Export ARM environment variables
        run: |
          echo "ARM_CLIENT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init #-backend-config=backend.tf

      - name: Terraform Validate
        run: terraform validate

      # - name: Terraform Plan
      #   id: tfplan
      #   run: |
      #     terraform plan -var-file="terraform.tfvars" -out=tfplan.out
      #     echo "plan_created=true" >> $GITHUB_OUTPUT

      # - name: Setup Infracost
      #   uses: infracost/actions/setup@v2.1.0
      #   with:
      #     api-key: ${{ secrets.INFRACOST_API_KEY }}

      # - name: Run Infracost Breakdown
      #   run: |
      #     infracost breakdown \
      #     --path=. \
      #     --terraform-plan-file=tfplan.out \
      #     --format=json \
      #     --out-file=infracost-report.json
      - name: Terraform Plan
        id: tfplan
        run: |
          terraform plan -var-file="terraform.tfvars" -out=tfplan.binary
          terraform show -json tfplan.binary > plan.json
          echo "plan_created=true" >> $GITHUB_OUTPUT
      
      - name: Setup Infracost
        uses: infracost/actions/setup@v2.1.0
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Run Infracost Breakdown
        run: |
          infracost breakdown \
          --path=plan.json \
          --format=json \
          --out-file=infracost-report.json
      - name: Show Infracost report saved info
        run: echo "INFO: Infracost report saved to infracost-report.json"

      # - name: Email Cost Estimate
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp.office365.com
      #     server_port: 587
      #     username: ${{ secrets.EMAIL_USER }}
      #     password: ${{ secrets.EMAIL_PASSWORD }}
      #     subject: "Infracost Report - ${{ env.ENV }}"
      #     to: prathyusha.y@algorims.com
      #     from: GitHub Terraform CI
      #     body: |
      #       Please find the attached Infracost report for Cosmos DB - ${{ env.ENV }}.
      #     attachments: infracost-report.json

  apply:
    name: Terraform Apply with Approval
    needs: plan
    runs-on: ubuntu-latest

    if: github.event.inputs.confirm_apply == 'yes'

    # ✅ GitHub Environments must be created as 'dev' and 'prod'
    environment: ${{ github.event.inputs.environment }}

    defaults:
      run:
        working-directory: terraform/environments/${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # - name: Azure Login
      #   uses: azure/login@v2
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Export ARM environment variables
        run: |
          echo "ARM_CLIENT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init   #-backend-config=backend.tf

      - name: Terraform Apply (waits for GitHub Environment approval)
        run: terraform apply -auto-approve tfplan.out