name: Terraform CosmosDB CI/CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (dev or prod)"
        required: true
        default: "dev"
      confirm_apply:
        description: "Type 'yes' to apply resources"
        required: true
        default: "no"

jobs:
  plan:
    name: Terraform Plan and Cost Estimate
    runs-on: ubuntu-latest

    env:
      ENV: ${{ github.event.inputs.environment }}

    defaults:
      run:
        working-directory: terraform/environments/${{ github.event.inputs.environment }}

    outputs:
      tfplan-exists: ${{ steps.tfplan.outputs.plan_created }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init -backend-config=backend.tf

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: tfplan
        run: |
          terraform plan -var-file="terraform.tfvars" -out=tfplan.out
          echo "plan_created=true" >> $GITHUB_OUTPUT

      - name: Generate Cost Estimate with Infracost
        uses: infracost/actions@vv2.1.3 
        with:
          path: terraform/environments/${{ env.ENV }}
          terraform_plan_file: tfplan.out
          terraform_workspace: ${{ env.ENV }}
          infracost_api_key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Email Cost Estimate
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Infracost Report for Cosmos DB - ${{ env.ENV }}"
          to: prathyusha.y@algorims.com
          from: GitHub Terraform CI
          body: |
            Please find the attached cost estimation for the Cosmos DB infrastructure changes.
          attachments: infracost-report.json

  apply:
    name: Terraform Apply
    needs: plan
    runs-on: ubuntu-latest

    if: github.event.inputs.confirm_apply == 'yes'

    environment: ${{ github.event.inputs.environment }}

    defaults:
      run:
        working-directory: terraform/environments/${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init -backend-config=backend.tf

      - name: Terraform Apply (with GitHub Environment approval)
        run: terraform apply -auto-approve tfplan.out
